package ASLENIX.pharmacy.demo.utils;

import ASLENIX.pharmacy.demo.model.InventoryBatch;
import ASLENIX.pharmacy.demo.model.Product;
import ASLENIX.pharmacy.demo.model.PurchaseOrder;
import ASLENIX.pharmacy.demo.model.Supplier;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class InventoryExcelExporter {

    public byte[] generate(List<InventoryBatch> list , String username) throws IOException {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = workbook.createSheet("PRODUCTS");

            setTitle(sheet, workbook, username);

            setHead(sheet,workbook);

            setBody(sheet, list);

            workbook.write(out);
            return out.toByteArray();
        }
    }

    private void setTitle(Sheet sheet, Workbook workbook, String username) {
        // --- Row 0: Main Title ---
        Row titleRow = sheet.createRow(0);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("INVENTORY CATALOG REPORT");

        // Styling for the title
        CellStyle titleStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        titleStyle.setFont(font);
        titleCell.setCellStyle(titleStyle);

        // Merge cells across 6 columns (A1 to F1)
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));

        // --- Row 1: Date ---
        Row metaRow1 = sheet.createRow(1);
        String todayDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        metaRow1.createCell(0).setCellValue("Generated On: " + todayDate);
        // --- Row 2: User ---
        Row metaRow2 = sheet.createRow(2);
        metaRow2.createCell(0).setCellValue("Generated By: " + (username != null ? username : "System"));
    }


    private void setHead(Sheet sheet, Workbook workbook) {
        // --- Row 4: Column Headers ---
        Row headerRow = sheet.createRow(4);

        // Header styling: Bold font with light gray background
        CellStyle headerStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        headerStyle.setFont(font);
        headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        // Exact requested column order
        String[] headers = {
                "BATCH NUMBER",
                "NAME OF PRODUCT",
                "QUANTITY RECEIVED",
                "STOCKS",
                "EXPIRY DATE",
                "SUPPLIER NAME",
                "COST PRICE",
                "SELLING PRICE",
                "STATUS",
                "STORAGE ZONE"
        };

        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
    }

    private void setBody(Sheet sheet, List<InventoryBatch> list) {
        // --- Rows 5+: Body Data ---
        int rowNum = 5;

        if (list == null || list.isEmpty()) {
            Row emptyRow = sheet.createRow(rowNum);
            emptyRow.createCell(0).setCellValue("No inventory batch available.");
            return;
        }

        for (InventoryBatch batch : list) {
            Row row = sheet.createRow(rowNum++);

            // Safely extract nested relationships to avoid NullPointerException
            Product product = batch.getProduct();
            PurchaseOrder po = batch.getPurchaseOrder();
            Supplier supplier = (po != null) ? po.getSupplier() : null;

            // 1. Batch Number
            row.createCell(0).setCellValue(
                    batch.getBatchNumber() != null ? batch.getBatchNumber() : "N/A"
            );

            // 2. Name of Product (Product Name + Generic Name)
            String productName = "N/A";
            if (product != null) {
                String name = product.getName() != null ? product.getName() : "";
                String genericName = product.getGenericName() != null ? product.getGenericName() : "";
                productName = genericName.isEmpty() ? name : name + " (" + genericName + ")";
            }
            row.createCell(1).setCellValue(productName);

            // 3. Quantity Received
            row.createCell(2).setCellValue(batch.getQuantityReceived());

            // 4. Stocks (Current Stock)
            row.createCell(3).setCellValue(batch.getCurrentStock());

            // 5. Expiry Date
            row.createCell(4).setCellValue(
                    batch.getExpiryDate() != null ? batch.getExpiryDate().toString() : "N/A"
            );

            // 6. Supplier Name (Navigated via PurchaseOrder -> Supplier)
            String supplierName = "N/A";
            if (supplier != null) {
                if (supplier.getSupplierName() != null) {
                    supplierName = supplier.getSupplierName();
                } else if (supplier.getCompanyName() != null) {
                    supplierName = supplier.getCompanyName();
                }
            }
            row.createCell(5).setCellValue(supplierName);

            // 7. Cost Price
            row.createCell(6).setCellValue(
                    batch.getCostPrice() != null ? batch.getCostPrice() : 0.0
            );

            // 8. Selling Price
            row.createCell(7).setCellValue(
                    batch.getSellingPrice() != null ? batch.getSellingPrice() : 0.0
            );

            // 9. Status (Batch Approval Status Enum)
            row.createCell(8).setCellValue(
                    batch.getBatchApprovalStatus() != null ? batch.getBatchApprovalStatus().name() : "N/A"
            );

            // 10. Storage Zone Enum
            row.createCell(9).setCellValue(
                    batch.getStorageZone() != null ? batch.getStorageZone().name() : "N/A"
            );
        }
    }

}
