package ASLENIX.pharmacy.demo.utils;

import ASLENIX.pharmacy.demo.model.Product;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ProductExcelExporter {

    public byte[] generate(List<Product> list , String username) throws IOException {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = workbook.createSheet("PRODUCTS");

            setTitle(sheet, workbook, username);

            setHead(sheet,workbook);

            setBody(sheet, list);

            workbook.write(out);
            return out.toByteArray();
        }
    }

    private void setTitle(Sheet sheet, Workbook workbook, String username) {
        // --- Row 0: Main Title ---
        Row titleRow = sheet.createRow(0);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("PRODUCT CATALOG REPORT");

        // Styling for the title
        CellStyle titleStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        titleStyle.setFont(font);
        titleCell.setCellStyle(titleStyle);

        // Merge cells across 6 columns (A1 to F1)
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));

        // --- Row 1: Date ---
        Row metaRow1 = sheet.createRow(1);
        String todayDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        metaRow1.createCell(0).setCellValue("Generated On: " + todayDate);

        // --- Row 2: User ---
        Row metaRow2 = sheet.createRow(2);
        metaRow2.createCell(0).setCellValue("Generated By: " + (username != null ? username : "System"));
    }

    private void setHead(Sheet sheet, Workbook workbook) {
        // --- Row 4: Column Headers ---
        Row headerRow = sheet.createRow(4);

        // Optional: Make header text bold with gray background
        CellStyle headerStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        headerStyle.setFont(font);
        headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        String[] headers = {
                "ID",
                "PRODUCT (Name - Generic)",
                "CATEGORY",
                "RACK LOCATION",
                "MIN STOCK",
                "DISCOUNT (%)"
        };

        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
    }


    private void setBody(Sheet sheet, List<Product> list) {
        // --- Rows 5+: Body Data ---
        int rowNum = 5;

        if (list == null || list.isEmpty()) {
            Row emptyRow = sheet.createRow(rowNum);
            emptyRow.createCell(0).setCellValue("No product records available.");
            return;
        }

        for (Product p : list) {
            Row row = sheet.createRow(rowNum++);

            // Col 0: ID
            row.createCell(0).setCellValue(p.getId() != null ? p.getId() : 0);

            // Col 1: Combined Product Name + Generic Name
            String name = p.getName() != null ? p.getName() : "";
            String genericName = p.getGenericName() != null ? p.getGenericName() : "";
            row.createCell(1).setCellValue(name + " - " + genericName);

            // Col 2: Category Name Only
            String catName = (p.getCategory() != null && p.getCategory().getCategoryName() != null)
                    ? p.getCategory().getCategoryName()
                    : "N/A";
            row.createCell(2).setCellValue(catName);

            // Col 3: Rack Location
            row.createCell(3).setCellValue(p.getRackLocation() != null ? p.getRackLocation() : "N/A");

            // Col 4: Min Stock Level
            row.createCell(4).setCellValue(p.getMinStockLevel() != null ? p.getMinStockLevel() : 0);

            // Col 5: Discount Percentage
            row.createCell(5).setCellValue(p.getDiscountPercentage() != null ? p.getDiscountPercentage() : 0.0);
        }
    }
}
