package ASLENIX.pharmacy.demo.utils;


import ASLENIX.pharmacy.demo.model.Product;
import ASLENIX.pharmacy.demo.model.User;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class UserExcelExporter {


    public byte[] generate(List<User> list , String username) throws IOException {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = workbook.createSheet("PRODUCTS");

            setTitle(sheet, workbook, username);

            setHead(sheet,workbook);

            setBody(sheet, list);

            workbook.write(out);
            return out.toByteArray();
        }
    }

    private void setTitle(Sheet sheet, Workbook workbook, String username) {
        // --- Row 0: Main Title ---
        Row titleRow = sheet.createRow(0);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("USER CATALOG REPORT");

        // Styling for the title
        CellStyle titleStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        titleStyle.setFont(font);
        titleCell.setCellStyle(titleStyle);

        // Merge cells across 6 columns (A1 to F1)
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));

        // --- Row 1: Date ---
        Row metaRow1 = sheet.createRow(1);
        String todayDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        metaRow1.createCell(0).setCellValue("Generated On: " + todayDate);

        // --- Row 2: User ---
        Row metaRow2 = sheet.createRow(2);
        metaRow2.createCell(0).setCellValue("Generated By: " + (username != null ? username : "System"));
    }

    private void setHead(Sheet sheet, Workbook workbook) {
        // --- Row 4: Column Headers ---
        Row headerRow = sheet.createRow(4);

        // Optional: Make header text bold with gray background
        CellStyle headerStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        headerStyle.setFont(font);
        headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        String[] headers = {
                "ID",
                "NAME",
                "USER NAME",
                "ROLE",
                "EMAIL",
                "STATUS",
                "CREATED AT"
        };

        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
    }


    private void setBody(Sheet sheet, List<User> list) {
        // --- Rows 5+: Body Data ---
        int rowNum = 5;

        if (list == null || list.isEmpty()) {
            Row emptyRow = sheet.createRow(rowNum);
            emptyRow.createCell(0).setCellValue("No USER available.");
            return;
        }

        for (User user : list) {
            Row row = sheet.createRow(rowNum++);

            // Col 0: ID
            row.createCell(0).setCellValue(user.getId() != null ? user.getId() : 0);

            // Col 1: Combined 1st Name + last Name
            String firstName = user.getFirstName() != null ? user.getFirstName() : "";
            String lastName = user.getLastName() != null ? user.getLastName() : "";
            row.createCell(1).setCellValue(firstName+ " - " + lastName);

            // Col 2 : userName
            String userName = user.getUsername() != null ? user.getUsername() : "";
            row.createCell(2).setCellValue(userName);

            // Col 3: role
            String role = user.getRole() != null ? user.getRole().getValue() : "N/A";
            row.createCell(3).setCellValue(role);

            // Col 4: email
            String email = user.getEmail() != null ? user.getEmail() : "N/A";
            row.createCell(4).setCellValue(user.getEmail() != null ? user.getEmail() : "N/A");

            // Col 5: status
            row.createCell(5).setCellValue(user.getStatus() != null ? user.getStatus().getValue() : "N/A");

            // Col 6: created at
            row.createCell(6).setCellValue(user.getCreatedAt() != null ? user.getCreatedAt().toString() : "");
        }
    }



}
