version: '3.8'

services:
  # Spring Boot Application Container
  app:
    build: .
    container_name: pharmacy-demo-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}        # Set your 3rd-party DB host in your .env file
      DB_PORT: ${DB_PORT}   # Set your 3rd-party DB port (default: 3306)
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}