$env:DB_PORT="3306"
$env:DB_NAME="DB_NAME"
$env:DB_USERNAME="DB_USERNAME"
$env:DB_PASSWORD="DB_PASSWORD"
$env:DOMAIN="DOMAIN"
$env:MAIL_PASSWORD="MAIL_PASSWORD"
$env:MAIL_USERNAME="MAIL_USERNAME"

.\mvnw.cmd spring-boot:run

